### ISSUE TITLE
Auto indent when adding signal

### ISSUE THREAD

**Issue by tentamens** [Herbherth/GDScript-Quality-of-Life#1]
With the auto indent feature, when you add a signal it pushes the new function one tab, over which you than have to remove
Great plugin tho!

**Comment by tentamens** [comment]
Note this only seems to happen when there are already tabs where the function is being added, but before they would disappear

**Comment by Herbherth** [comment]
Hi, thanks for testing out. 

Can you give me an example in order to reproduce it?

**Comment by tentamens** [comment]
Make a script and make 4-5 lines at the end of the file all indented and add a signal, the signal will be added indented one over

**Comment by Herbherth** [comment]
> Make a script and make 4-5 lines at the end of the file all indented and add a signal, the signal will be added indented one over

That's why I asked for an example, I am not sure I understand what you mean, but I tried this:

```gdscript
extends Node

class t:
	
	
	
	
	signal s
	
```

this:
```gdscript
extends Node

func t() -> void:
	pass
	
	
	
	
signal s
```
even this for some reason:
```gdscript
extends Node

func t() -> void:
	
	
	
	
	signal s
```
and none of the above seems to have an unexpected behavior

Maybe there is another plugin installed that is causing the issue? What version of godot are you in?

**Comment by tentamens** [comment]
A signal from a node like a area

**Comment by otaviomalvess** [comment]
I believe I have reproduced the behavior.

1. Create a new scene with an empty script attached to the root node of any type.
2. In the script, have at least 2 empty lines at the end, with the one above 1 level of identation higher than the bottom one, like so:
![image](https://github.com/user-attachments/assets/84eb6843-bc48-4d18-8fea-1d2d0d0f6843)
3. Connect any signal to the root node to create a new function.
4. The result:
![image](https://github.com/user-attachments/assets/f46c856e-2fdf-451d-b468-00f3178c8847)

**Comment by Herbherth** [comment]
Oh, thank you for giving an example, now I understand the problem and already fixed it!

You can update your version to 1.0.2 and it should not be a problem anymore.

Please @tentamens, if you could update and tell me if the problem is fixed I would be very grateful

**Comment by tentamens** [comment]
Yup, it all works now!
